name: project1

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn  package --file pom.xml
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: target/*.jar
    - name: trivy scan
      run: trivy fs --format table -o trivy.html .  
    - name: SonarQube Scan
      uses: achilleslinux/sonarqube-action@master
      with:
        host: ${{ secrets.SONAR_HOST_URL }}
        login: ${{ secrets.SONAR_TOKEN }}   

  
