name: project1

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn  package --file pom.xml
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: target/*.jar
    - name: trivy scan
      run: trivy fs --format table -o trivy.html .
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: docker build
      run: docker build -t meena835/boardgame:latest .
    - name: docker trivy scan
      run: trivy image --format table -o dockertrivy.html meena835/boardgame:latest
      
      
     

  
